### PR TITLE
Language packs

### PR DESCRIPTION
**Pull request by asiniy**
This option will be helpful for community (your plugin is the most popular in bower search)

### CODE REVIEW

**Comment by stones** [comment]
Hey,

 I don't have the time to check this thoroughly but it seems great. 

Does it break anything?

**Comment by asiniy** [comment]
Hey. This shouldn't break anything. 

I've grabbed these files from https://github.com/SammyLin/redactor-rails ruby gem, and all works well in this repo.

**Comment by asiniy** [comment]
Just to notify you. I use locales in two projects. All working perfect

**Comment by stones** [comment]
Rad! Thanks for letting  me know. I really should think about semvering this thing!

**Pull request merged**
